/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/scan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Scan */
        post: operations["scan_api_scan_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/emulate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Emulate */
        post: operations["emulate_api_emulate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/defang": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Defang */
        post: operations["defang_api_defang_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** DefangRequest */
        DefangRequest: {
            /** Repo Url */
            repo_url: string;
        };
        /** Defanged */
        Defanged: {
            /** Files Removed */
            files_removed?: string[];
            /** Files Modified */
            files_modified?: string[];
            /**
             * Output Path
             * @default
             */
            output_path: string;
        };
        /** EmulateRequest */
        EmulateRequest: {
            /** Repo Url */
            repo_url: string;
            /**
             * Offline
             * @default false
             */
            offline: boolean;
        };
        /**
         * Emulation
         * @description Result of extracting the IDE's own trigger paths and executing only those.
         *
         *     Not "we ran the repo in a sandbox" -- Cursor is not running in our container, so
         *     that would reproduce nothing. We parse tasks.json / mcp.json, extract the exact
         *     commands the IDE would execute on folder open, and run those under tracing.
         */
        Emulation: {
            /**
             * Ran
             * @default false
             */
            ran: boolean;
            /**
             * Reason
             * @default
             */
            reason: string;
            /** Triggers Extracted */
            triggers_extracted?: string[];
            /** Processes */
            processes?: string[];
            /** Files Written */
            files_written?: string[];
            /** Network Attempts */
            network_attempts?: string[];
        };
        /**
         * Finding
         * @description One hostile artifact found in the repo.
         *
         *     Note there is deliberately no `severity` field. Severity is what every scanner
         *     emits and it means nothing to a reader. `blast_radius` -- what this payload would
         *     actually reach -- is the useful thing, and tracing already produces it.
         */
        Finding: {
            /**
             * Vector
             * @enum {string}
             */
            vector: "rules_file" | "mcp_json" | "tasks_json" | "planted_binary";
            /** File */
            file: string;
            /**
             * Blast Radius
             * @default
             */
            blast_radius: string;
            /**
             * Evidence
             * @default
             */
            evidence: string;
            /**
             * Decoded
             * @default
             */
            decoded: string;
            /**
             * Visible Chars
             * @default 0
             */
            visible_chars: number;
            /**
             * Model Chars
             * @default 0
             */
            model_chars: number;
            /**
             * Explanation
             * @default
             */
            explanation: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** ScanReport */
        ScanReport: {
            /**
             * Repo Url
             * @default
             */
            repo_url: string;
            /**
             * Verdict
             * @default clean
             * @enum {string}
             */
            verdict: "quarantined" | "clean";
            /**
             * Kill Chain
             * @default
             */
            kill_chain: string;
            /** Findings */
            findings?: components["schemas"]["Finding"][];
            emulation?: components["schemas"]["Emulation"];
            defanged?: components["schemas"]["Defanged"];
        };
        /** ScanRequest */
        ScanRequest: {
            /** Repo Url */
            repo_url: string;
            /**
             * Use Ai
             * @default true
             */
            use_ai: boolean;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    scan_api_scan_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScanRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScanReport"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    emulate_api_emulate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EmulateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Emulation"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    defang_api_defang_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DefangRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScanReport"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
